services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.2
    container_name: elastic
    restart: no
    ports:
      - "9200:9200"
    networks:
      - monitoring
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    volumes:
      - elastic-volume:/usr/share/elasticsearch/data
networks:
  monitoring:
volumes:
  grafana-volume:
    external: true
  elastic-volume:
    external: true